let array = new Uint8Array(-INSERTAR_ARRAY-);
let data=new DataView(array.buffer);

let turianSendData = new Map()
turianSendData.set("navigationData",0)

let navigationData = new Map()
navigationData.set("imu2Data",0)

let imu2Data = new Map()
imu2Data.set("gyrX",data.getInt16(0,true))
imu2Data.set("gyrY",data.getInt16(2,true))
imu2Data.set("gyrZ",data.getInt16(4,true))
imu2Data.set("accelX",data.getInt16(6,true))
imu2Data.set("accelY",data.getInt16(8,true))
imu2Data.set("accelZ",data.getInt16(10,true))
navigationData.set("imu2Data",imu2Data)
navigationData.set("tapesData",0)

let tapesData = new Map()
tapesData.set("globalTapeCount",data.getInt16(12,true))
tapesData.set("direction",data.getInt8(14))
tapesData.set("tapeErrors",data.getUint32(15,true))
navigationData.set("tapesData",tapesData)
navigationData.set("dist_run",data.getFloat32(19,true))
navigationData.set("speed",data.getFloat32(23,true))
navigationData.set("naviAmbient",0)

let naviAmbient = new Map()
naviAmbient.set("bmp280Temperature",data.getInt8(27))
naviAmbient.set("bmp280Pressure",data.getUint32(28,true))
navigationData.set("naviAmbient",naviAmbient)
turianSendData.set("navigationData",navigationData)
turianSendData.set("bmshData",[])

let bmshData = new Map()
bmshData.set("bmshBattery",[])

let bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(32))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(33))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(34))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(35))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(36))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(37))
bmshData.set("output_current",data.getFloat32(38,true))
bmshData.set("output_total_voltage",data.getFloat32(42,true))
bmshData.set("min_voltage",data.getFloat32(46,true))
bmshData.set("max_voltage",data.getFloat32(50,true))
turianSendData.get("bmshData").push(bmshData)

bmshData = new Map()
bmshData.set("bmshBattery",[])

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(54))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(55))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(56))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(57))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(58))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(59))
bmshData.set("output_current",data.getFloat32(60,true))
bmshData.set("output_total_voltage",data.getFloat32(64,true))
bmshData.set("min_voltage",data.getFloat32(68,true))
bmshData.set("max_voltage",data.getFloat32(72,true))
turianSendData.get("bmshData").push(bmshData)

bmshData = new Map()
bmshData.set("bmshBattery",[])

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(76))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(77))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(78))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(79))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(80))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(81))
bmshData.set("output_current",data.getFloat32(82,true))
bmshData.set("output_total_voltage",data.getFloat32(86,true))
bmshData.set("min_voltage",data.getFloat32(90,true))
bmshData.set("max_voltage",data.getFloat32(94,true))
turianSendData.get("bmshData").push(bmshData)

bmshData = new Map()
bmshData.set("bmshBattery",[])

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(98))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(99))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(100))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(101))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(102))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(103))
bmshData.set("output_current",data.getFloat32(104,true))
bmshData.set("output_total_voltage",data.getFloat32(108,true))
bmshData.set("min_voltage",data.getFloat32(112,true))
bmshData.set("max_voltage",data.getFloat32(116,true))
turianSendData.get("bmshData").push(bmshData)

bmshData = new Map()
bmshData.set("bmshBattery",[])

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(120))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(121))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(122))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(123))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(124))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(125))
bmshData.set("output_current",data.getFloat32(126,true))
bmshData.set("output_total_voltage",data.getFloat32(130,true))
bmshData.set("min_voltage",data.getFloat32(134,true))
bmshData.set("max_voltage",data.getFloat32(138,true))
turianSendData.get("bmshData").push(bmshData)

bmshData = new Map()
bmshData.set("bmshBattery",[])

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(142))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(143))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(144))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(145))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(146))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(147))
bmshData.set("output_current",data.getFloat32(148,true))
bmshData.set("output_total_voltage",data.getFloat32(152,true))
bmshData.set("min_voltage",data.getFloat32(156,true))
bmshData.set("max_voltage",data.getFloat32(160,true))
turianSendData.get("bmshData").push(bmshData)

bmshData = new Map()
bmshData.set("bmshBattery",[])

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(164))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(165))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(166))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(167))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(168))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(169))
bmshData.set("output_current",data.getFloat32(170,true))
bmshData.set("output_total_voltage",data.getFloat32(174,true))
bmshData.set("min_voltage",data.getFloat32(178,true))
bmshData.set("max_voltage",data.getFloat32(182,true))
turianSendData.get("bmshData").push(bmshData)

bmshData = new Map()
bmshData.set("bmshBattery",[])

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(186))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(187))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(188))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(189))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(190))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(191))
bmshData.set("output_current",data.getFloat32(192,true))
bmshData.set("output_total_voltage",data.getFloat32(196,true))
bmshData.set("min_voltage",data.getFloat32(200,true))
bmshData.set("max_voltage",data.getFloat32(204,true))
turianSendData.get("bmshData").push(bmshData)

bmshData = new Map()
bmshData.set("bmshBattery",[])

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(208))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(209))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(210))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(211))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(212))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(213))
bmshData.set("output_current",data.getFloat32(214,true))
bmshData.set("output_total_voltage",data.getFloat32(218,true))
bmshData.set("min_voltage",data.getFloat32(222,true))
bmshData.set("max_voltage",data.getFloat32(226,true))
turianSendData.get("bmshData").push(bmshData)

bmshData = new Map()
bmshData.set("bmshBattery",[])

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(230))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(231))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(232))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(233))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(234))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(235))
bmshData.set("output_current",data.getFloat32(236,true))
bmshData.set("output_total_voltage",data.getFloat32(240,true))
bmshData.set("min_voltage",data.getFloat32(244,true))
bmshData.set("max_voltage",data.getFloat32(248,true))
turianSendData.get("bmshData").push(bmshData)

bmshData = new Map()
bmshData.set("bmshBattery",[])

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(252))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(253))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(254))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(255))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(256))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(257))
bmshData.set("output_current",data.getFloat32(258,true))
bmshData.set("output_total_voltage",data.getFloat32(262,true))
bmshData.set("min_voltage",data.getFloat32(266,true))
bmshData.set("max_voltage",data.getFloat32(270,true))
turianSendData.get("bmshData").push(bmshData)

bmshData = new Map()
bmshData.set("bmshBattery",[])

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(274))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(275))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(276))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(277))
bmshData.get("bmshBattery").push(bmshBattery)

bmshBattery = new Map()
bmshBattery.set("temperature",data.getUint8(278))
bmshData.get("bmshBattery").push(bmshBattery)
bmshData.set("extra_temperature_sensor",data.getUint8(279))
bmshData.set("output_current",data.getFloat32(280,true))
bmshData.set("output_total_voltage",data.getFloat32(284,true))
bmshData.set("min_voltage",data.getFloat32(288,true))
bmshData.set("max_voltage",data.getFloat32(292,true))
turianSendData.get("bmshData").push(bmshData)
turianSendData.set("bmsaData",[])

let bmsaData = new Map()
bmsaData.set("cell",[])

let cell = new Map()
cell.set("charge",data.getUint16(296,true))
cell.set("voltage",data.getUint16(298,true))
bmsaData.get("cell").push(cell)

cell = new Map()
cell.set("charge",data.getUint16(300,true))
cell.set("voltage",data.getUint16(302,true))
bmsaData.get("cell").push(cell)

cell = new Map()
cell.set("charge",data.getUint16(304,true))
cell.set("voltage",data.getUint16(306,true))
bmsaData.get("cell").push(cell)

cell = new Map()
cell.set("charge",data.getUint16(308,true))
cell.set("voltage",data.getUint16(310,true))
bmsaData.get("cell").push(cell)
bmsaData.set("current",data.getUint8(312))
bmsaData.set("temperature",[])
bmsaData.get("temperature").push(data.getUint8(313))
bmsaData.get("temperature").push(data.getUint8(314))
bmsaData.set("voltage_max",data.getUint16(315,true))
bmsaData.set("voltage_min",data.getUint16(317,true))
bmsaData.set("voltage_GBL_state",data.getUint8(319))
turianSendData.get("bmsaData").push(bmsaData)

bmsaData = new Map()
bmsaData.set("cell",[])

cell = new Map()
cell.set("charge",data.getUint16(320,true))
cell.set("voltage",data.getUint16(322,true))
bmsaData.get("cell").push(cell)

cell = new Map()
cell.set("charge",data.getUint16(324,true))
cell.set("voltage",data.getUint16(326,true))
bmsaData.get("cell").push(cell)

cell = new Map()
cell.set("charge",data.getUint16(328,true))
cell.set("voltage",data.getUint16(330,true))
bmsaData.get("cell").push(cell)

cell = new Map()
cell.set("charge",data.getUint16(332,true))
cell.set("voltage",data.getUint16(334,true))
bmsaData.get("cell").push(cell)
bmsaData.set("current",data.getUint8(336))
bmsaData.set("temperature",[])
bmsaData.get("temperature").push(data.getUint8(337))
bmsaData.get("temperature").push(data.getUint8(338))
bmsaData.set("voltage_max",data.getUint16(339,true))
bmsaData.set("voltage_min",data.getUint16(341,true))
bmsaData.set("voltage_GBL_state",data.getUint8(343))
turianSendData.get("bmsaData").push(bmsaData)
turianSendData.set("brakesData",0)

let brakesData = new Map()
brakesData.set("high_press1",data.getFloat32(344,true))
brakesData.set("high_press2",data.getFloat32(348,true))
brakesData.set("mid_press",data.getFloat32(352,true))
brakesData.set("low_press",data.getFloat32(356,true))
brakesData.set("temp0",data.getInt8(360))
brakesData.set("temp1",data.getInt8(361))
brakesData.set("temp2",data.getInt8(362))
brakesData.set("temp3",data.getInt8(363))
brakesData.set("pos_acts",data.getUint8(364))
brakesData.set("solenoid_state",data.getUint8(365))
turianSendData.set("brakesData",brakesData)
turianSendData.set("turian",0)

let turian = new Map()
turian.set("mosfet",data.getUint8(366))
turian.set("timeStamp",data.getUint32(367,true))
turianSendData.set("turian",turian)
turianSendData.set("motorStatatus",0)

let motorStatatus = new Map()
motorStatatus.set("motorC",[])
motorStatatus.get("motorC").push(data.getFloat32(371,true))
motorStatatus.get("motorC").push(data.getFloat32(375,true))
motorStatatus.get("motorC").push(data.getFloat32(379,true))
motorStatatus.get("motorC").push(data.getFloat32(383,true))
motorStatatus.get("motorC").push(data.getFloat32(387,true))
motorStatatus.get("motorC").push(data.getFloat32(391,true))
motorStatatus.get("motorC").push(data.getFloat32(395,true))
motorStatatus.get("motorC").push(data.getFloat32(399,true))
motorStatatus.get("motorC").push(data.getFloat32(403,true))
motorStatatus.get("motorC").push(data.getFloat32(407,true))
motorStatatus.get("motorC").push(data.getFloat32(411,true))
motorStatatus.get("motorC").push(data.getFloat32(415,true))
motorStatatus.set("motorV",[])
motorStatatus.get("motorV").push(data.getFloat32(419,true))
motorStatatus.get("motorV").push(data.getFloat32(423,true))
motorStatatus.get("motorV").push(data.getFloat32(427,true))
motorStatatus.get("motorV").push(data.getFloat32(431,true))
motorStatatus.get("motorV").push(data.getFloat32(435,true))
motorStatatus.get("motorV").push(data.getFloat32(439,true))
motorStatatus.get("motorV").push(data.getFloat32(443,true))
motorStatatus.get("motorV").push(data.getFloat32(447,true))
motorStatatus.get("motorV").push(data.getFloat32(451,true))
motorStatatus.get("motorV").push(data.getFloat32(455,true))
motorStatatus.get("motorV").push(data.getFloat32(459,true))
motorStatatus.get("motorV").push(data.getFloat32(463,true))
turianSendData.set("motorStatatus",motorStatatus)
